<?php

use App\Constant\CustomTokenType;
use App\Constant\RouteName;
use Zus1\LaravelAuth\Constant\Token\TokenType;

return [
    'user_namespace' => env('LARAVEL_AUTH_USER_NAMESPACE', 'App\Models'),
    'user_class' => sprintf(
        '%s\\%s',
        env('LARAVEL_AUTH_USER_NAMESPACE', 'App\Models'),
        env('LARAVEL_AUTH_USER_CLASS', 'User')
    ),

    'token' => [
        'expires_in' => [
            'access_token' => 30 * 24 * 60,
            'refresh_token' => 60 * 24 * 60,
            'user_verification_token' => 60,
            'reset_password_token' => 30,
        ],
        'length' => [
            'access_token' => 100,
            'refresh_token' => 100,
            'user_verification_token' => 50,
            'reset_password_token' => 50,
        ],
        'type_class' => CustomTokenType::class,
        'request_header' => 'Authorization'
    ],
    'email' => [
        'subject' => [
            'verification' => 'Email verification',
            'reset_password' => 'Reset Password',
            'welcome' => 'Welcome',
            'invitation' => 'Student onboarding'
        ],
        'templates' => [
            'verification' => [
                'txt' => 'mail/authentication::verify-txt',
                'markdown' => 'mail/authentication::verify'
            ],
            'reset_password' => [
                'txt' => 'mail/authentication::reset-password-txt',
                'markdown' => 'mail/authentication::reset-password'
            ],
            'welcome' => [
                'txt' => 'mail/authentication::welcome-txt',
                'markdown' => 'mail/authentication::welcome'
            ],
            'invitation' => [
                'txt' => 'auth.invitation-txt',
                'markdown' => 'auth.invitation'
            ],
        ],
        'redirect_url' => [
            'invitation' => env('AUTH_INVITATION_REDIRECT_URL'),
        ],
    ],

    'authorization' => [
        'mapping' => [
            RouteName::STUDENT_CREATE => 'create',
            RouteName::STUDENT_UPDATE => 'update',
            RouteName::STUDENT_DELETE => 'delete',
            RouteName::STUDENT => 'retrieve',
            RouteName::STUDENTS => 'collection',
            RouteName::TEACHER_UPDATE => 'pass',
            RouteName::TEACHER_DELETE => 'pass',
            RouteName::TEACHER => 'pass',
            RouteName::TEACHERS => 'pass',
            RouteName::GUARDIAN_UPDATE => 'update',
            RouteName::GUARDIAN_DELETE => 'delete',
            RouteName::GUARDIAN => 'retrieve',
            RouteName::GUARDIANS => 'collection',
            RouteName::USER_TOGGLE_ACTIVE => 'toggleActive',
            RouteName::ME_DELETE => 'meDelete',
            RouteName::CALENDAR_CREATE => 'pass',
            RouteName::CALENDAR_UPDATE => 'pass',
            RouteName::CALENDAR_DELETE => 'pass',
            RouteName::CALENDAR_TOGGLE_ACTIVE => 'pass',
            RouteName::CALENDARS => 'pass',
            RouteName::EVENT_CREATE => 'create',
            RouteName::EVENT_UPDATE => 'update',
            RouteName::EVENT_DELETE => 'delete',
            RouteName::EVENT => 'retrieve',
            RouteName::EVENTS => 'collection',
            RouteName::EVENT_TOGGLE_NOTIFY => 'toggleNotify',
            RouteName::EVENT_UPDATE_STATUS => 'updateStatus',
            RouteName::EVENT_UPDATE_REPEATABLE_STATUS => 'updateRepeatableStatus',
            RouteName::SUBJECT_CREATE => 'pass',
            RouteName::SUBJECT_UPDATE => 'pass',
            RouteName::SUBJECT_DELETE => 'pass',
            RouteName::SUBJECT_TOGGLE_LECTURER => 'pass',
            RouteName::SUBJECT_TOGGLE_LECTURER_CLASSES => 'pass',
            RouteName::TEACHER_SUBJECT => 'pass',
            RouteName::TEACHER_SUBJECTS => 'pass',
            RouteName::CLASSROOM_CREATE => 'create',
            RouteName::CLASSROOM_UPDATE => 'update',
            RouteName::CLASSROOM_DELETE => 'delete',
            RouteName::CLASSROOM => 'retrieve',
            RouteName::CLASSROOMS => 'collection',
            RouteName::CLASSROOM_TOGGLE_EQUIPMENT => 'toggleEquipment',
            RouteName::CLASSROOM_UPDATE_EQUIPMENT_QUANTITY => 'updateEquipmentQuality',
            RouteName::EQUIPMENT_CREATE => 'pass',
            RouteName::EQUIPMENT_UPDATE => 'pass',
            RouteName::EQUIPMENT_DELETE => 'pass',
            RouteName::EQUIPMENT => 'pass',
            RouteName::EQUIPMENTS => 'pass',
            RouteName::MESSAGE_CREATE => 'create',
            RouteName::MESSAGE_UPDATE => 'update',
            RouteName::MESSAGE_DELETE => 'delete',
            RouteName::MESSAGE => 'retrieve',
            RouteName::MESSAGES => 'collection',
            RouteName::MESSAGES_MARK_AS_READ => 'markAsRead',
            RouteName::GRADE_CREATE => 'create',
            RouteName::GRADE_UPDATE => 'update',
            RouteName::GRADE_DELETE => 'delete',
            RouteName::GRADES => 'collection',
            RouteName::ATTENDANCE_CREATE => 'create',
            RouteName::ATTENDANCE_UPDATE => 'update',
            RouteName::ATTENDANCE_DELETE => 'delete',
            RouteName::ATTENDANCES => 'collection',
            RouteName::ATTENDANCES_AGGREGATE => 'aggregate',
            RouteName::GRADING_RULE_CREATE => 'create',
            RouteName::GRADING_RULE_UPDATE => 'update',
            RouteName::GRADING_RULE_DELETE => 'delete',
            RouteName::GRADING_RULE => 'retrieve',
            RouteName::GRADING_RULES => 'collection',
            RouteName::GRADE_RANGE_CREATE => 'create',
            RouteName::GRADE_RANGE_UPDATE => 'update',
            RouteName::GRADE_RANGE_DELETE => 'delete',
            RouteName::EXAM_CREATE => 'create',
            RouteName::EXAM_UPDATE => 'update',
            RouteName::EXAM_DELETE => 'delete',
            RouteName::EXAM => 'retrieve',
            RouteName::EXAMS => 'collection',
            RouteName::EXAM_TOGGLE_GRADING_RULE => 'toggleGradingRule',
            RouteName::EXAM_TOGGLE_ALLOWED_SCHOOL_CLASS => 'toggleAllowedClass',
            RouteName::QUESTIONS_CREATE => 'create',
            RouteName::QUESTION_UPDATE => 'update',
            RouteName::QUESTION_DELETE => 'delete',
            RouteName::QUESTION => 'retrieve',
            RouteName::QUESTIONS => 'collection',
            RouteName::QUESTION_CHANGE_EXAM => 'changeExam',
            RouteName::ANSWER_UPDATE => 'update',
            RouteName::ANSWER_DELETE => 'delete',
            RouteName::ANSWER_CHANGE_QUESTION => 'changeQuestion',
            RouteName::EXAM_RESPONSE_CREATE => 'create',
            RouteName::EXAM_RESPONSE_UPDATE => 'update',
            RouteName::EXAM_RESPONSE_DELETE => 'delete',
            RouteName::EXAM_RESPONSE => 'retrieve',
            RouteName::EXAM_RESPONSES => 'collection',
            RouteName::EXAM_SESSION_CREATE => 'create',
            RouteName::EXAM_SESSION_DELETE => 'delete',
            RouteName::EXAM_SESSION_FINISH => 'finish',
            RouteName::EXAM_SESSION_GRADE => 'grade',
            RouteName::EXAM_SESSION => 'retrieve',
            RouteName::EXAM_SESSIONS => 'collection',
            RouteName::ACTIVITY_TRACKINGS => 'collection',
            RouteName::PRODUCT => 'retrieve',
            RouteName::PRODUCTS => 'collection',
            RouteName::PAYMENT => 'retrieve',
            RouteName::PAYMENTS => 'collection',
        ],
        'possible_route_parameters' => [
            'student', 'teacher', 'guardian', 'user', 'calendar', 'recipient', 'grade',
            'event', 'classroom', 'subject', 'teacherSubject', 'equipment', 'message',
            'attendance', 'gradingRule', 'gradeRange', 'exam', 'question', 'answer',
            'examResponse', 'examSession', 'product', 'payment',
        ],
        'additional_subjects' => [
            RouteName::STUDENT_CREATE => \App\Models\Student::class,
            RouteName::STUDENTS => \App\Models\Student::class,
            RouteName::TEACHERS => \App\Models\Teacher::class,
            RouteName::GUARDIANS => \App\Models\Guardian::class,
            RouteName::ME_DELETE => \App\Models\Guardian::class,
            RouteName::CALENDARS => \App\Models\Calendar::class,
            RouteName::EVENTS => \App\Models\Event::class,
            RouteName::SUBJECT_CREATE => \App\Models\Subject::class,
            RouteName::TEACHER_SUBJECTS => \App\Models\TeacherSubject::class,
            RouteName::CLASSROOM_CREATE => \App\Models\Classroom::class,
            RouteName::CLASSROOMS => \App\Models\Classroom::class,
            RouteName::EQUIPMENT_CREATE => \App\Models\Equipment::class,
            RouteName::EQUIPMENTS => \App\Models\Equipment::class,
            RouteName::MESSAGE_CREATE => \App\Models\Message::class,
            RouteName::MESSAGES_MARK_AS_READ => \App\Models\Message::class,
            RouteName::GRADE_CREATE => \App\Models\Grade::class,
            RouteName::GRADES => \App\Models\Grade::class,
            RouteName::ATTENDANCE_CREATE => \App\Models\Attendance::class,
            RouteName::ATTENDANCES => \App\Models\Attendance::class,
            RouteName::ATTENDANCES_AGGREGATE => \App\Models\Attendance::class,
            RouteName::GRADING_RULE_CREATE => \App\Models\GradingRule::class,
            RouteName::GRADING_RULES => \App\Models\GradingRule::class,
            RouteName::GRADE_RANGE_CREATE => \App\Models\GradeRange::class,
            RouteName::EXAM_CREATE => \App\Models\Exam::class,
            RouteName::EXAMS => \App\Models\Exam::class,
            RouteName::QUESTIONS_CREATE => \App\Models\Question::class,
            RouteName::QUESTIONS => \App\Models\Question::class,
            RouteName::EXAM_RESPONSE_CREATE => \App\Models\ExamResponse::class,
            RouteName::EXAM_RESPONSES => \App\Models\ExamResponse::class,
            RouteName::EXAM_SESSION_CREATE => \App\Models\ExamSession::class,
            RouteName::EXAM_SESSIONS => \App\Models\ExamSession::class,
            RouteName::ACTIVITY_TRACKINGS => \App\Models\ActivityTracking::class,
            RouteName::PRODUCTS => \App\Models\Product::class,
            RouteName::PAYMENTS => \App\Models\Payment::class,
        ],
        'subject_overrides' => [
            RouteName::ME_DELETE => \App\Models\Guardian::class
        ],
    ]
];
